language: cpp
sudo: false
branches:
  only:
  - master
  - travis
  - /^v\d+(\.\d+)+$/
  - travis_build
matrix:
  include:
  - os: linux
    arch: arm64
    dist: trusty
    addons:
      apt:
        packages:
        - gfortran
        - zlib1g-dev
        - libhdf5-dev
  - os: osx
    arch: arm64
    osx_image: xcode10.4.4
    sudo: required
before_install:
      #curl -L -o gfortran-7.1-bin.tgz -fs "https://downloads.sourceforge.net/project/hpc/hpc/g95/gfortran-7.1-bin.tar.gz?r=&ts=1508458128&use_mirror=svwh"
      #gunzip gfortran-7.1-bin.tgz
      #sudo tar -xf gfortran-7.1-bin.tar -C /
      #sudo chown -R $(whoami) /usr/local
      #sudo chown -R $(whoami) /Library/Caches/Homebrew
      #brew update
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then 
      brew install szip
      rm '/usr/local/include/c++'
      #brew install --verbose --debug --force hdf5@1.8 --c++11
      brew install hdf5@1.8
    fi
    
script: .travis/build.sh

# for osx, use otool -L to find dependencies
# for linux, use ldd to find dependencies
# copy dependent libraries to build/bin (excluding those already in the build/bin directory ... -v "build")
# (for mac only) edit executables and libraries using install_name_tool to make relocatable
# create compressed tar file to deploy to github
before_deploy:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      cd build/bin
      ls *_x64   | awk '{print $1}' | xargs -I '{}' otool -L '{}' | grep ")" | grep -v "build" | grep -v "System" | awk '{print $1}' | xargs -I '{}' cp -vn '{}' . || true
      ls *.dylib | awk '{print $1}' | xargs -I '{}' otool -L '{}' | grep ")" | grep -v "build" | grep -v "System" | awk '{print $1}' | xargs -I '{}' cp -vn '{}' . || true
      ls *.dylib | awk '{print $1}' | xargs -I '{}' otool -L '{}' | grep ")" | grep -v "build" | grep -v "System" | awk '{print $1}' | xargs -I '{}' cp -vn '{}' . || true
      chmod u+w,+x * 
      tar czvf ../mac64_bad_paths.tgz .
      ../../.travis/install_name_tool_macos.sh
      tar czvf ../mac64.tgz --dereference .
      cd ../..
    else
      cd build/bin
      ls *_x64   | awk '{print $1}' | xargs -I '{}' ldd '{}' | grep "=> /" | grep -v "build" | awk '{print $3}' | xargs -I '{}' cp -vn '{}' . || true
      ls *.so    | awk '{print $1}' | xargs -I '{}' ldd '{}' | grep "=> /" | grep -v "build" | awk '{print $3}' | xargs -I '{}' cp -vn '{}' . || true
      ls *.so    | awk '{print $1}' | xargs -I '{}' ldd '{}' | grep "=> /" | grep -v "build" | awk '{print $3}' | xargs -I '{}' cp -vn '{}' . || true
      chmod u+w,+x *
      tar czvf ../linux64.tgz --dereference .
      cd ../..
    fi

deploy:
  provider: releases
  api_key:
    secure: AC0CIp66mYfJckp1cNkz6Ko2lH5qg0ouE55GJjkncNgDKdRahksuHJ8OvKTQeozj4c5Jk1rNUCit+n+CfkZ63ibOupZx4YD2t/oD2enfYV78Zr6TDJ4apT4tF1yk006HmT2aIQ1zk5aJia1+jqkHSudfFC/zBg1MbdB0fhG0sECTs3KhKeC7IEzvybykNe7/o0GvlA3gXQ8joH0uoDC0urb4dbqPoAAavqoEkNh5afW6qY/gJX1fo+VDEPFTfv6ZmPTtmUUFLfLnvwhm97ALPsDpfMmbVwDj+GwQWsA8wsbb56VNDzxITXlZfflRqhCnlwpZDbCqtlbeADBbNfn9Pxw/SkU9vcuv3aiiNuY1yZvFC6yXWFBCtcPXmNMPYpJP5H8Df0mZE3Ca475Zg/1eTPOiThelePhCxDUwEs1n+ipbaB+sKZJpvz8sUlMNNQy0YWBP71vDuLB2ZL1LiI2REIbEnpkwJXRBJwP9ZSPzph8hq0CFw1AwPSodhX9w9Q9Ggro+K3vVvZm2yzEgvU91HiW7xgZAki3pq51S/50F85CnBnTFRy2OWSRXBIx1KNrN6MrwycBUx68bnwji+HlbOL6pR879vCoDyyUjt0mtHIZZPRqd+au0ZhI1fSnQfRmJuo/Jz7vl0TdZMi2gHXwmax2P5qQw3U7Vh0iUdq3tRJk=
  file_glob: true
  file: build/*.tgz
  skip_cleanup: true
  on:
    repo: virtualcell/vcell-solvers
    tags: true
    all_branches: true
